### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by Yurunsoft**
* Support for running in non-coroutine
* Fix multiple definition of `startTime'
* Improve test cases
* Fix type of $timeout in ZooKeeper::__construct()
* Add github actions test
* Add ZOO_LOG_LEVEL constants and set default debug level
* Set default debug level
* Fix some Segmentation fault (core dumped)

### CODE REVIEW

**Comment by heyanlong** [comment]
Why add `docker-compose.yml` to `.github` DIR? I think it should in docker DIR.

**Comment by Yurunsoft** [comment]
This `docker-compose.yml` is used for testing.

How about moving it to `tests`?

**Comment by heyanlong** [comment]
I think it's in `docker` for other in use.

**Comment by Yurunsoft** [comment]
The args are a bit much and I don't think it's quite right for others to use

**Pull request merged**
